import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
import uvicorn
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
import requests

app = FastAPI(title="RootTrace AI Worker")

class IncidentData(BaseModel):
    incidentId: str
    logs: List[str]
    traceGraph: Optional[dict] = None
    metrics: Optional[List[dict]] = None
    repo_url: Optional[str] = None
    github_token: Optional[str] = None

@app.get("/")
async def root():
    return {"message": "RootTrace AI Worker is running"}

@app.post("/analyze")
async def analyze_incident(data: IncidentData):
    # Day 5: AI RCA Engine
    try:
        if os.getenv("OPENAI_API_KEY"):
            llm = ChatOpenAI(model="gpt-4-turbo", temperature=0)
            prompt = ChatPromptTemplate.from_messages([
                ("system", "You are an expert Site Reliability Engineer. Analyze the following incident logs, traces, and metrics to determine the root cause, confidence score, evidence, and recommended actions. Output JSON."),
                ("user", "Incident Logs: {logs}\nTraces: {traces}\nMetrics: {metrics}")
            ])
            chain = prompt | llm
            # In a real scenario we parse the output, but we mock it below for demo
            
        root_cause = "Simulated: Database connection timeout in 'user-service' due to high connection pool usage."
        evidence = ["Log: TimeoutException getting connection", "Trace: user-service -> database took > 5000ms"]
        recommended_actions = ["Increase HikariCP max pool size", "Investigate slow queries in user profile fetching"]
            
    except Exception as e:
        print(f"LLM analysis failed, using fallback: {e}")
        root_cause = "Database connection timeout in 'user-service'"
        evidence = ["Log: TimeoutException"]
        recommended_actions = ["Increase HikariCP max pool size"]

    # Day 6: GitHub Fix Suggestion
    pr_url = None
    if data.repo_url and data.github_token:
        try:
            headers = {
                "Authorization": f"token {data.github_token}",
                "Accept": "application/vnd.github.v3+json"
            }
            parts = data.repo_url.rstrip('/').split('/')
            owner, repo = parts[-2], parts[-1]
            if repo.endswith('.git'):
                repo = repo[:-4]
                
            issue_data = {
                "title": f"RootTrace Auto-Fix: Incident {data.incidentId}",
                "body": f"### Root Cause\n{root_cause}\n\n### Evidence\n{evidence}\n\n### Recommended Actions\n{recommended_actions}\n\n*Generated by RootTrace AI*"
            }
            res = requests.post(f"https://api.github.com/repos/{owner}/{repo}/issues", json=issue_data, headers=headers)
            if res.status_code == 201:
                pr_url = res.json().get("html_url")
        except Exception as e:
            print(f"Failed to create GitHub issue: {e}")

    return {
        "incidentId": data.incidentId,
        "rootCause": root_cause,
        "confidence": 0.95,
        "evidence": evidence,
        "recommendedActions": recommended_actions,
        "githubIssueUrl": pr_url
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
